### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by cn-hideyoshi** [cn-hideyoshi/auto-sms-go#1]
1. add xsql to connect mysql
2. add rabbitmq support
3. add redis support

**Comment by cn-hideyoshi** [comment]
- [x] add xsql to connect mysql
- [ ] add rabbitmq support
- [ ] add redis support

**Comment by cn-hideyoshi** [comment]
- [x] add xsql to connect mysql
- [x] add redis support
- [ ] add rabbitmq support
